// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrebaNam.API;

#nullable disable

namespace TrebaNam.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260906180708_PartialAmounts")]
    partial class PartialAmounts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text")
                        .HasColumnName("friendly_name");

                    b.Property<string>("Xml")
                        .HasColumnType("text")
                        .HasColumnName("xml");

                    b.HasKey("Id")
                        .HasName("pk_data_protection_keys");

                    b.ToTable("data_protection_keys", (string)null);
                });

            modelBuilder.Entity("TrebaNam.API.Auth.UserEntity", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email_address");

                    b.Property<string>("GivenName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("given_name");

                    b.Property<string>("GoogleSub")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("google_sub");

                    b.Property<Guid?>("HouseholdID")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin");

                    b.Property<DateTimeOffset>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("PictureUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("picture_url");

                    b.Property<string>("Surname")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("surname");

                    b.HasKey("ID")
                        .HasName("pk_users");

                    b.HasIndex("GoogleSub")
                        .IsUnique()
                        .HasDatabaseName("ix_users_google_sub");

                    b.HasIndex("HouseholdID")
                        .HasDatabaseName("ix_users_household_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TrebaNam.API.Households.HouseholdEntity", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserID")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("invite_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.HasKey("ID")
                        .HasName("pk_households");

                    b.HasIndex("InviteCode")
                        .IsUnique()
                        .HasDatabaseName("ix_households_invite_code");

                    b.ToTable("households", (string)null);
                });

            modelBuilder.Entity("TrebaNam.API.Items.ItemEntity", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AddedByUserID")
                        .HasColumnType("uuid")
                        .HasColumnName("added_by_user_id");

                    b.Property<string>("BoughtQuantity")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("bought_quantity");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("HouseholdID")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_checked");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Quantity")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("quantity");

                    b.HasKey("ID")
                        .HasName("pk_items");

                    b.HasIndex("HouseholdID")
                        .HasDatabaseName("ix_items_household_id");

                    b.ToTable("items", (string)null);
                });

            modelBuilder.Entity("TrebaNam.API.ShoppingRecords.ShoppingRecordEntity", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("CompletedByUserID")
                        .HasColumnType("uuid")
                        .HasColumnName("completed_by_user_id");

                    b.Property<Guid>("HouseholdID")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.HasKey("ID")
                        .HasName("pk_shopping_records");

                    b.HasIndex("HouseholdID")
                        .HasDatabaseName("ix_shopping_records_household_id");

                    b.ToTable("shopping_records", (string)null);
                });

            modelBuilder.Entity("TrebaNam.API.ShoppingRecords.ShoppingRecordItemEntity", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("category");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Quantity")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("ShoppingRecordID")
                        .HasColumnType("uuid")
                        .HasColumnName("shopping_record_id");

                    b.HasKey("ID")
                        .HasName("pk_shopping_record_items");

                    b.HasIndex("ShoppingRecordID")
                        .HasDatabaseName("ix_shopping_record_items_shopping_record_id");

                    b.ToTable("shopping_record_items", (string)null);
                });

            modelBuilder.Entity("TrebaNam.API.Auth.UserEntity", b =>
                {
                    b.HasOne("TrebaNam.API.Households.HouseholdEntity", null)
                        .WithMany()
                        .HasForeignKey("HouseholdID")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_users_households_household_id");
                });

            modelBuilder.Entity("TrebaNam.API.Items.ItemEntity", b =>
                {
                    b.HasOne("TrebaNam.API.Households.HouseholdEntity", null)
                        .WithMany()
                        .HasForeignKey("HouseholdID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_items_households_household_id");
                });

            modelBuilder.Entity("TrebaNam.API.ShoppingRecords.ShoppingRecordEntity", b =>
                {
                    b.HasOne("TrebaNam.API.Households.HouseholdEntity", null)
                        .WithMany()
                        .HasForeignKey("HouseholdID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shopping_records_households_household_id");
                });

            modelBuilder.Entity("TrebaNam.API.ShoppingRecords.ShoppingRecordItemEntity", b =>
                {
                    b.HasOne("TrebaNam.API.ShoppingRecords.ShoppingRecordEntity", null)
                        .WithMany("Items")
                        .HasForeignKey("ShoppingRecordID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shopping_record_items_shopping_records_shopping_record_id");
                });

            modelBuilder.Entity("TrebaNam.API.ShoppingRecords.ShoppingRecordEntity", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
